// index.js
const express = require('express');
const firebaseAdmin = require('firebase-admin');
const app = express();
const port = process.env.PORT || 3000;

app.use(express.json()); // Middleware to parse JSON bodies

// Initialize Firebase Admin SDK with Service Account JSON
firebaseAdmin.initializeApp({
  credential: firebaseAdmin.credential.cert({
    "type": "service_account",
    "project_id": "applicationofloan-a33d2",
    "private_key_id": "YOUR_PRIVATE_KEY_ID",
    "private_key": process.env.FIREBASE_PRIVATE_KEY.replace(/\\n/g, '\n'),
    "client_email": "YOUR_CLIENT_EMAIL",
    "client_id": "YOUR_CLIENT_ID",
    "auth_uri": "https://accounts.google.com/o/oauth2/auth",
    "token_uri": "https://oauth2.googleapis.com/token",
    "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
    "client_x509_cert_url": "YOUR_CLIENT_X509_CERT_URL"
  }),
  databaseURL: "https://applicationofloan-a33d2-default-rtdb.firebaseio.com"
});

// Get Firebase Realtime Database reference
const db = firebaseAdmin.database();

// Sample GET endpoint
app.get('/api/hello', (req, res) => {
  res.json({ message: 'Hello from Koyeb with Firebase!' });
});

// Registration endpoint using Firebase Realtime Database
app.post('/api/register', async (req, res) => {
  const { name, email, number } = req.body;

  // Validation
  if (!name || !email || !number) {
    return res.status(400).json({ error: 'Name, email, and number are required' });
  }

  try {
    // Save data to Firebase Realtime Database
    const userRef = db.ref('users').push();
    await userRef.set({ name, email, number });

    res.json({
      message: 'Registration successful!',
      userId: userRef.key, // Unique key generated by Firebase
      user: { name, email, number },
    });
  } catch (error) {
    console.error('Error adding user:', error);
    res.status(500).json({ error: 'Failed to register user' });
  }
});

// Start the server
app.listen(port, () => {
  console.log(`Server is running on http://localhost:${port}`);
  console.log(`Production URL: https://your-koyeb-url.koyeb.app`);
});
