// index.js
const express = require('express');
const db = require('./firebaseConfig'); // Import Firebase configuration
const app = express();
const port = process.env.PORT || 3000;

app.use(express.json()); // Middleware to parse JSON bodies

// Sample GET endpoint
app.get('/api/hello', (req, res) => {
  res.json({ message: 'Hello from Koyeb with Firebase!' });
});

// Registration endpoint using Firebase Realtime Database
app.post('/api/register', async (req, res) => {
  const { name, email, number } = req.body;

  // Validation
  if (!name || !email || !number) {
    return res.status(400).json({ error: 'Name, email, and number are required' });
  }

  try {
    // Save data to Firebase Realtime Database
    const userRef = db.ref('koyel').push();
    await userRef.set({ name, email, number });

    res.json({
      message: 'Registration successful!',
      userId: userRef.key, // Unique key generated by Firebase
      user: { name, email, number },
    });
  } catch (error) {
    console.error('Error adding user:', error);
    res.status(500).json({ error: 'Failed to register user' });
  }
});

// Start the server
app.listen(port, () => {
  console.log(`Server is running on http://localhost:${port}`);
  console.log(`Production URL: https://your-koyeb-url.koyeb.app`); // Update with your actual production URL
});
